# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test123ertyg5

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_45dda576f8c7459ea3bc54972adb9b0c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a290666297f94e94a4633d72f9f7574e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_45dda576f8c7459ea3bc54972adb9b0c }}/saimaheshpb/assessment-repo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test123ertyg5'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b8d8b7db0d324594a7213f005599863e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_45dda576f8c7459ea3bc54972adb9b0c }}/saimaheshpb/assessment-repo:${{ github.sha }}'